project:
  type: website
  output-dir: docs

website:
  title: "b-causal.org"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/go-bayes
      - icon: mastodon
        href: https://fosstodon.org/@b_causal
format:
  html:
    theme: cosmo
    css: styles.css

license: CC BY-NC-SA