project:
  type: website

website:
  title: "b-causal"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/go-bayes
      - icon: twitter
        href: https://twitter.com/prof_joe_
format:
  html:
    theme: cosmo
    css: styles.css



