project:
  type: website
  output-dir: docs

website:
  title: "b-causal-lab brief reports"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/go-bayes
      - icon: twitter
        href: https://twitter.com/prof_joe_
format:
  html:
    theme: cosmo
    css: styles.css

license: CC BY-NC-SA


