---
title: "Change in Covid Attitudes from 2021 - 2022"
execute:
  warning: false
  echo: false
draft: false
citation:
  url: https://go-bayes.github.io/b-causal/
date: 2022-11-11
date-format: short
categories: 
  - NZAVS
  - Covid
---

```{r}
#| echo: false
# covid omnibus
# joseph bulbulia  1 NOV 2022

# options(future.globals.maxSize = 8000 * 1024 ^ 2)  # needed
# set science digits
options(scipen = 999)

# function for installing dependencies
ipak <- function(pkg){
  new.pkg <- pkg[!(pkg %in% installed.packages()[, "Package"])]
  if (length(new.pkg))
    install.packages(new.pkg, dependencies = TRUE)
  sapply(pkg, require, character.only = TRUE)
}
# usage
packages <- c("tidyverse",
              "remotes",
              "devtools",
              "janitor",
              "here",
              "purrr",
              "ggplot2",
              "stdReg",
              "mice",
              "miceadds",
              "Amelia",
              "conflicted",
              "naniar",
              "skimr",
              "marginaleffects",
              "splines",
             # "CMAverse",
              "gghighlight",
              "formula.tools",
              "ggpubr",
              "lme4",
              "rstan",
              "cmdstanr",
              "geepack",
              "brms",
              "ggokabeito",
              "table1",
              "kableExtra",
              "parameters",
              "lubridate",
              "patchwork",
              "katex",
               "gt",
             "gtsummary",
              "tidyr")
ipak(packages)


# next install rethinking
# if (!require(rethinking)) {
#   devtools::install_github("rmcelreath/rethinking")
# }

if (!require(CMAverse)) {
  devtools::install_github("BS1125/CMAverse")
}


if (!require(CMAverse)) {
  remotes::install_github("ddsjoberg/gtsummary")
}



# install.packages("remotes")

if (!require(cmdstanr)) {
 remotes::install_github("stan-dev/cmdstanr")
 install_cmdstan() 
}

# # libraries and functions
# # read libraries
# source("https://raw.githubusercontent.com/go-bayes/templates/main/functions/libs.R")

# read functions
# source("https://raw.githubusercontent.com/go-bayes/templates/main/functions/funs.R")

# for saving models  # ONLY FOR JOSEPH BULUBLIA -- SET TO YOUR PREFERRED FOLDERS
push_mods <-
  fs::path_expand("~/The\ Virtues\ Project\ Dropbox/outcomewide/mods")
push_figs <-
  fs::path_expand("~/Users/joseph/The\ Virtues\ Project\ Dropbox/outcomewide/figs")

# read data # ONLY FOR JOSEPH BULUBLIA
pull_path <-
  fs::path_expand(
    "~/The\ Virtues\ Project\ Dropbox/Joseph\ Bulbulia/00Bulbulia\ Pubs/2021/DATA/ldf.5"
  )

# read data
dt <- readRDS(pull_path)
```


```{r}
#| label: inspect covid vars

# inspect 
cvd_vars = c(
  "COVID19.Timeline",
  "COVID.RiskCatching",
  "COVID.Rumination",
  "COVID.ConfidentRecovery",
  "COVID.RisksExaggerated",
  "COVID.CreatedLab",
  "COVID.InfoSourceGovt",
  "COVID.InfoSourceNewsMedia",
  "COVID.InfoSourceSocialMedia",
  "COVID.SatGovtResponse",
  "COVID.TrustGovtResponse",
  "COVID.ComplianceTesting",
  "COVID.ComplianceVaccinate",
  "COVID.ComplianceMask",
  "COVID.ComplianceIsolateHome",
  "COVID.ComplianceContactTrace",
  "COVID.ComplianceAllMoHGuidelines",
  "COVID.BeenTested",
  "COVID.RequestTest",
  "COVID.DeclineReq",
  "COVID.Vaccinated",
  "COVID.VaccinatedIntend",
  "COVID.VaccinationSafe",
  "COVID.VaccinatedRefusal"

)
cvd_vars

dt2 <- dt |>
  dplyr::filter(
           (Wave == "2020" & YearMeasured == 1) |
          (Wave == "2021" & YearMeasured == 1))  |>
  dplyr::select(c(all_of(cvd_vars), Wave, YearMeasured, TSCORE, Id))

length(unique(dt2$Id))



out2 <- paste0(cvd_vars,
      collapse = "+" )
out2<- noquote(out2)



# filter just the data we need
dt3 <- dt2 |>
 dplyr::filter(Wave == 2020 | Wave == 2021)
# 
# table1::table1( ~ COVID.RisksExaggerated+COVID.CreatedLab+COVID.SatGovtResponse+COVID.TrustGovtResponse+COVID.Vaccinated+COVID.VaccinatedIntend+COVID.VaccinationSafe|Wave, data = dt2, overall =FALSE)



trial_summary <- dt3 %>% 
  group_by(Wave)%>% 
  tbl_summary(vars(cvd_vars)) 
```


```{r, include = FALSE}

dt_temp <- dt2 |> select(Wave,
                         COVID.RisksExaggerated,
                         COVID.CreatedLab,
                         COVID.SatGovtResponse,
                         COVID.TrustGovtResponse
                        # COVID.Vaccinated,
                        # COVID.VaccinatedIntend,
                        # COVID.VaccinationSafe
                        )





dt_long <- pivot_longer(dt_temp,
                        cols = -c("Wave"),
                        names_prefix = "COVID.",
                        values_to = "Values",
                        names_to = "Target"
) |> drop_na()


dev.off()
ggplot(dt_long, aes(x=Target, y=Values, color=Target)) +
  geom_violin() +  coord_flip() +  scale_fill_brewer(palette="RdBu") + theme_minimal()
```


```{r}
#| label: boxplot change


#notch = TRUE, outlier.colour="red", outlier.shape=8,
#outlier.size=4

# https://ggplot2tutor.com/tutorials/summary_statistics

# cov_values <- dt_long|>
#   dplyr::mutate(Target = forcats::fct_reorder(Target, desc(Values))) |>
#   ggplot2::ggplot(aes(Target, Values, fill = Target)) +
#   labs(title = "Covid Attitudes/Behaviours NZ 2021 (N = 33,000)") +
#   geom_violin(size =.05 ) +  scale_fill_viridis_d() +
#   facet_grid (.~ Wave, scales = "free_x", space = "free_x") +
#   theme(legend.position = "none")
#   cov_values
# 
#   dev.off()


cov_values <- dt_long |>
  dplyr::mutate(Target = forcats::fct_reorder(Target, desc(Values))) |>
  ggplot2::ggplot(aes(Target, Values, fill = Target)) +
  labs(title = "Covid Attitudes NZ 2020/21 to 2021/22 (N = 43,853)") +
  geom_boxplot(size = .05, notch = T) +  scale_fill_viridis_d() +
  facet_grid (. ~ Wave, scales = "free_x", space = "free_x") +
  # coord_flip() +
  theme(legend.position = "none")

cov_values

ggsave(
  cov_values,
  path = here::here(here::here("posts", "covid-change")),
  width = 9,
  height = 9,
  units = "in",
  filename = "covid-change.png",
  device = 'png',
  limitsize = FALSE,
  dpi = 100
)

```

